### ISSUE TITLE
Checklist for registering / v0.1.0

### ISSUE THREAD

**Issue by mortenpi** [JuliaDocs/DocumenterTools.jl#10]
Just putting small stuff here so we wouldn't forget.

- [ ] Update installation instructions in the README.
- [ ] Fix #14
- [ ] Add REQUIRE since it is needed for registering in Metadata
- [ ] Update the uuid to be metadata compatible.
